package domain

import "time"

type URL struct {
	// ID is the unique identifier for the URL. int64 is used to allow for a large number of URLs.
	ID int64 `json:"id"`

	// original url from user
	Original string `json:"original_url"`

	// shortened url generated by the service
	ShortCode string `json:"short_code"`

	//This is a timestamp that shows when the entry was created. use for analytics.
	CreatedAt time.Time `json:"created_at"`
}
